apiVersion: v2
name: rancher-cluster-templates
description: Hardened Rancher Cluster Templates by Rancher Government Solutions
icon: https://raw.githubusercontent.com/rancherfederal/carbide-docs/main/static/img/carbide-logo.svg
type: application
version: 0.5.0
appVersion: 0.5.0
annotations:
  catalog.cattle.io/type: cluster-template
  catalog.cattle.io/namespace: fleet-default
