{{- if .Values.addons.monitoring }}
{{- if .Values.addons.monitoring.enabled }}
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: monitoring-crd-{{ .Values.cluster.name }}
  namespace: fleet-default
spec:
  chart: "rancher-monitoring-crd"
  repoName: "rancher-charts"
  releaseName: "rancher-monitoring-crd"
  version: {{ .Values.addons.monitoring.version }}
  {{- if .Values.addons.monitoring.values }}
  values:
{{ toYaml .Values.addons.monitoring.values | indent 4 }}
  {{- end }}
  defaultNamespace: "cattle-monitoring-system"
  targets:
  - clusterName: {{ .Values.cluster.name }}
---
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: monitoring-{{ .Values.cluster.name }}
  namespace: fleet-default
spec:
  chart: "rancher-monitoring"
  repoName: "rancher-charts"
  releaseName: "rancher-monitoring"
  version: {{ .Values.addons.monitoring.version }}
  {{- if .Values.addons.monitoring.values }}
  values:
{{ toYaml .Values.addons.monitoring.values | indent 4 }}
  {{- end }}
  defaultNamespace: "cattle-monitoring-system"
  targets:
  - clusterName: {{ .Values.cluster.name }}
  diff:
    comparePatches:
    - apiVersion: admissionregistration.k8s.io/v1beta1
      kind: MutatingWebhookConfiguration
      name: rancher-monitoring-admission
      jsonPointers:
      - /webhooks/0/failurePolicy
    - apiVersion: admissionregistration.k8s.io/v1beta1
      kind: ValidatingWebhookConfiguration
      name: rancher-monitoring-admission
      jsonPointers:
      - /webhooks/0/failurePolicy
    - apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      name: rancher-monitoring-kubelet
      namespace: kube-system
      jsonPointers:
      - /spec/endpoints
---
{{- end }}
{{- end }}
{{- if .Values.addons.longhorn }}
{{- if .Values.addons.longhorn.enabled }}
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: longhorn-crd-{{ .Values.cluster.name }}
  namespace: fleet-default
spec:
  chart: "longhorn-crd"
  repoName: "rancher-charts"
  releaseName: "longhorn-crd"
  version: {{ .Values.addons.longhorn.version }}
  {{- if .Values.addons.longhorn.values }}
  values:
{{ toYaml .Values.addons.longhorn.values | indent 4 }}
  {{- end }}
  defaultNamespace: "longhorn-system"
  targets:
  - clusterName: {{ .Values.cluster.name }}
  diff:
    comparePatches:
      - apiVersion: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: engineimages.longhorn.io
        jsonPointers:
          - /status/acceptedNames
          - /status/conditions
          - /status/storedVersions
      - apiVersion: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: nodes.longhorn.io
        jsonPointers:
          - /status/acceptedNames
          - /status/conditions
          - /status/storedVersions
      - apiVersion: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: volumes.longhorn.io
        jsonPointers:
          - /status/acceptedNames
          - /status/conditions
          - /status/storedVersions
---
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: longhorn-{{ .Values.cluster.name }}
  namespace: fleet-default
spec:
  chart: "longhorn"
  repoName: "rancher-charts"
  releaseName: "longhorn"
  version: {{ .Values.addons.longhorn.version }}
  {{- if .Values.addons.longhorn.values }}
  values:
{{ toYaml .Values.addons.longhorn.values | indent 4 }}
  {{- end }}
  defaultNamespace: "longhorn-system"
  targets:
  - clusterName: {{ .Values.cluster.name }}
---
{{- end }}
{{- end }}
{{- if .Values.addons.neuvector }}
{{- if .Values.addons.neuvector.enabled }}
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: neuvector-crd-{{ .Values.cluster.name }}
  namespace: fleet-default
spec:
  chart: "neuvector-crd"
  repoName: "rancher-charts"
  releaseName: "neuvector-crd"
  version: {{ .Values.addons.neuvector.version }}
  {{- if .Values.addons.neuvector.values }}
  values:
{{ toYaml .Values.addons.neuvector.values | indent 4 }}
  {{- end }}
  defaultNamespace: "cattle-neuvector-system"
  targets:
  - clusterName: {{ .Values.cluster.name }}
---
apiVersion: management.cattle.io/v3
kind: ManagedChart
metadata:
  name: neuvector-{{ .Values.cluster.name }}
  namespace: fleet-default
spec:
  chart: "neuvector"
  repoName: "rancher-charts"
  releaseName: "neuvector"
  version: {{ .Values.addons.neuvector.version }}
  {{- if .Values.addons.neuvector.values }}
  values:
{{ toYaml .Values.addons.neuvector.values | indent 4 }}
  {{- end }}
  defaultNamespace: "cattle-neuvector-system"
  targets:
  - clusterName: {{ .Values.cluster.name }}
---
{{- end }}
{{- end }}
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-calico
  namespace: kube-system
spec:
  valuesContent: |-
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
            - key: topology.kubernetes.io/region
              operator: In
              values:
              - jp-east-2
          weight: 100
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: Exists
    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          k8s-app: tigera-operator
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          k8s-app: tigera-operator
    tolerations:
    - effect: NoExecute
      operator: Exists
    - effect: NoSchedule
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 30
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 30
    installation:
      calicoNetwork:
        nodeAddressAutodetectionV4:
          kubernetes: NodeInternalIP
      controlPlaneTolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - effect: NoExecute
          key: node-role.kubernetes.io/etcd
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 30
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 30
      calicoKubeControllersDeployment:
        spec:
          template:
            spec:
              affinity:
                nodeAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                  - preference:
                      matchExpressions:
                      - key: topology.kubernetes.io/region
                        operator: In
                        values:
                        - jp-east-2
                    weight: 100
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: node-role.kubernetes.io/worker
                        operator: Exists
      calicoNodeDaemonSet:
        spec:
          template:
            spec:
              tolerations:
              - key: CriticalAddonsOnly
                operator: Exists
              - effect: NoSchedule
                operator: Exists
              - effect: NoExecute
                operator: Exists
              - effect: NoExecute
                key: node.kubernetes.io/not-ready
                operator: Exists
                tolerationSeconds: 30
              - effect: NoExecute
                key: node.kubernetes.io/unreachable
                operator: Exists
                tolerationSeconds: 30
      typhaDeployment:
        spec:
          template:
            spec:
              affinity:
                nodeAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                  - preference:
                      matchExpressions:
                      - key: topology.kubernetes.io/region
                        operator: In
                        values:
                        - jp-east-2
                    weight: 100
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: node-role.kubernetes.io/worker
                        operator: Exists

